
name: Flatten middle folder (google-blog → /)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  flatten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout google-blog branch
        uses: actions/checkout@v4
        with:
          ref: google-blog
          fetch-depth: 0

      - name: Make safety backup branch
        run: |
          git config user.name "OngsBot"
          git config user.email "bot@ongsblog.com"
          git checkout -b backup/pre-flatten-$(date +%Y%m%d-%H%M%S)
          git push -u origin HEAD
          git checkout google-blog

      - name: Flatten if middle folder exists
        shell: bash
        run: |
          set -e
          if [ -d "google-blog" ]; then
            git mv -k google-blog/* . || true
            git mv -k google-blog/.[!.]* . || true
            git mv -k google-blog/..?* . || true
            # 폴더 비우기 & 제거
            git rm -r --ignore-unmatch google-blog || true
            git add -A
            git commit -m "chore: flatten repo — move google-blog/* to repo root" || echo "No changes to commit"
            git push origin HEAD:google-blog
            echo "✅ Flatten OK"
          else
            echo "ℹ️ No middle folder 'google-blog' — nothing to do."
          fi
